modLoader="javafml"
loaderVersion="[64,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Nanonaitor/Nanonaitors-Defenders/issues"

[[mods]]
modId="defenders"
version="1.1.1"
displayName="Nanonaitor's Defenders"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nanonaitors-defenders"
logoFile="assets/defenders/logo.png"
authors="Nanonaitor"
description='''Off-hand melee shield-weapons with perfect parries, active guarding, material identities, and configurable combat mechanics.'''

[[dependencies.defenders]]
modId="forge"
mandatory=true
versionRange="[64,)"
ordering="NONE"
side="BOTH"

[[dependencies.defenders]]
modId="minecraft"
mandatory=true
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"
